## PyTorch
### Objective: To familiarize with PyTorch fundamentals

In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

print(torch.get_num_threads())

2.12.0+cpu
False
4


### Vector vs Tensor
A tensor is a generalized multidimensional array, while a vector is a one-dimensional tensor.


In [ ]:
scalar = torch.tensor(7)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar: {scalar.shape}")

In [ ]:

vec = torch.tensor([3,4,5,6])
print(vec)
print(f"Dimension of vec: {vec.ndim}")
print(f"Shape of vec: {vec.shape}")

In [3]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(f"Dimension of ten: {matrix.ndim}")
print(f"Shape of ten: {matrix.shape}")
matrix

Dimension of ten: 2
Shape of ten: torch.Size([3, 3])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR.ndim)
print(TENSOR.shape)
TENSOR

3
torch.Size([1, 3, 3])


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Scalar

A scalar is a single numerical value represented as a 0-dimensional tensor.

In [12]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
print(scalar.ndim)
print(scalar.item()) 
print(scalar.shape)

0
7
torch.Size([])


### Vector
A vector is a 1-dimensional tensor containing multiple values arranged in a single axis.

In [9]:
vector = torch.tensor([3,4,5,6])
vector

tensor([3, 4, 5, 6])

In [10]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


### Matrix
A matrix is a 2-dimensional tensor consisting of rows and columns.

In [11]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Tensor
A tensor is a multi-dimensional data structure used to store and process data in deep learning.
It can represent complex data such as images, videos, and datasets.

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

## Tensor Creation Functions

PyTorch provides various functions to create tensors quickly for different purposes such as random initialization, zero initialization, and identity matrices.

1. torch.rand() - Creates a tensor with random values.
2. torch.zeros() - Creates a tensor filled with zeros.
3. torch.ones() - Creates a tensor filled with ones.
4. torch.eye() - Creates an identity matrix.
5. torch.arange() - Generates a sequence of values with a fixed step.
6. torch.linspace() - Generates evenly spaced values within a range.

In [13]:
rand = torch.rand(3,4)
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
eye = torch.eye(3)
arange = torch.arange(start=0, end=10, step=2)
linspace = torch.linspace(start=0, end=10, steps=5)

print(f"rand: {rand}")
print(f"zeros: {zeros}")
print(f"ones: {ones}")
print(f"eye: {eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")

rand: tensor([[0.8034, 0.8943, 0.1829, 0.9532],
        [0.0353, 0.1988, 0.9096, 0.2681],
        [0.5170, 0.8173, 0.5733, 0.2088]])
zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## Tensor Arithmetic
Arithmetic operations can be performed directly on tensors. These operations are applied element-wise.

### `+` Operator

The `+` operator is used for element-wise addition between tensors.\
It provides a simple and readable syntax that is easy to understand.\
A new tensor is created to store the result of the addition.\
It automatically supports broadcasting when tensor shapes are compatible.\
It is the most commonly used method for tensor addition in PyTorch.

### `torch.add()`

`torch.add()` is a PyTorch function used for element-wise tensor addition.\
It produces the same result as the `+` operator in normal addition operations.\
It provides additional parameters such as `alpha` for scaling values before addition.\
It also supports the `out` parameter for storing results in a specified tensor.\
It is useful when greater control over memory usage and computations is required.


In [14]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])

print(a+b)
print(a-b)
print(a*b)

# adding using add()
print(torch.add(a,b))

print(torch.add(a, b, alpha=2))

tensor([4, 6, 8])
tensor([-2, -2, -2])
tensor([ 3,  8, 15])
tensor([4, 6, 8])
tensor([ 7, 10, 13])


## @ vs. * for Tensor Multiplication

#### * (Element-wise Multiplication)
The * operator performs element-wise multiplication between tensors.\
Each element of the first tensor is multiplied by the corresponding element of the second tensor.\
The tensors must have the same shape or compatible shapes through broadcasting.\
The output tensor has the same shape as the input tensors.\
It is commonly used for scaling values and feature-wise operations.
#### @ (Matrix Multiplication)
The @ operator performs matrix multiplication between tensors.\
It follows the rules of linear algebra, where inner dimensions must match.\
For matrices, the number of columns in the first tensor must equal the number of rows in the second tensor.\
The resulting tensor shape is determined by the outer dimensions.\
It is widely used in deep learning for operations such as neural network computations and linear transformations.

In [15]:
# Element-wise multiplication (*)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"Tensor A: {a}")
print(f"Tensor B: {b}")
print(f"Element-wise multiplication (A * B): {a * b}")

# Matrix multiplication (@)
mat_a = torch.tensor([[1, 2],
                      [3, 4]])
mat_b = torch.tensor([[5, 6],
                      [7, 8]])

print(f"\nMatrix A: {mat_a}")
print(f"Matrix B: {mat_b}")
print(f"Matrix multiplication (A @ B): {mat_a @ mat_b}")

# Example with 1D tensors (dot product)
vec_a = torch.tensor([1, 2, 3])
vec_b = torch.tensor([4, 5, 6])

print(f"\nVector A: {vec_a}")
print(f"Vector B: {vec_b}")
print(f"Dot product (Vector A @ Vector B): {vec_a @ vec_b}")

Tensor A: tensor([1, 2, 3])
Tensor B: tensor([4, 5, 6])
Element-wise multiplication (A * B): tensor([ 4, 10, 18])

Matrix A: tensor([[1, 2],
        [3, 4]])
Matrix B: tensor([[5, 6],
        [7, 8]])
Matrix multiplication (A @ B): tensor([[19, 22],
        [43, 50]])

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot product (Vector A @ Vector B): 32


## Memory Behavior

The main difference is how they handle memory sharing.

A view means the new tensor uses the same underlying memory as the original tensor.
A copy means a new separate memory block is created.

### tensor.view()
Always tries to return a view (no new memory allocation).
Both tensors share the same data in memory.
So, changing one tensor affects the other.
Requires the tensor to be contiguous in memory (data stored in a clean, continuous layout).
If not contiguous (e.g., after transpose), view() will fail unless you call .contiguous() first, which may create a copy.

Key idea: Strict but memory-efficient

### tensor.reshape()
More flexible than view().
First tries to return a view if possible.
If the memory layout is not suitable, it automatically creates a copy.
Works even with non-contiguous tensors.

Key idea: Flexible but may use extra memory

In [17]:
t = torch.arange(11, 20, 1)  # values from 10 to 18

print(t.reshape(3, 3))
print(t.view(3, 3))
print(t)

tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])


#### squeeze() and unsqueeze()
squeeze() removes dimensions of size 1, while unsqueeze() adds a dimension of size 1 at a specified position.

In [18]:
x = torch.tensor([[[4.0], [5.0], [6.0]]])

print(x.shape)
print(x.squeeze())        
print(x.squeeze().shape)

print(x.unsqueeze(1)) 

torch.Size([1, 3, 1])
tensor([4., 5., 6.])
torch.Size([3])
tensor([[[[4.],
          [5.],
          [6.]]]])


#### torch.stack()
torch.stack() combines multiple tensors into a single tensor by creating a new dimension.

In [19]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([7, 8, 9])

print(torch.stack([a, b, c], dim=0)) 
print(torch.stack([a, b, c], dim=1)) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


## Indexing and Aggregation
Indexing allows access to specific elements of a tensor, while aggregation functions such as min(), max(), mean(), and sum() provide summary statistics.

In [20]:
t = torch.tensor([[2., 4., 7.],
                  [1., 9., 8.]])

print(t.min(), t.max())
print(t.mean(), t.sum())
print(t.argmin(), t.argmax())

print(t[1])       
print(t[:, 0])     
print(t[0, 2]) 

tensor(1.) tensor(9.)
tensor(5.1667) tensor(31.)
tensor(3) tensor(4)
tensor([1., 9., 8.])
tensor([2., 1.])
tensor(7.)


## Datatype and dtype Casting
Every tensor has a data type. Type casting is used to convert tensors from one data type to another when required.

In [ ]:
x = torch.tensor([1, 2, 3])
print(x.dtype)   # torch.int64 by default

f = x.type(torch.float32)
print(f)
print(f.dtype)

# or specify at creation
y = torch.tensor([1.0, 2.0], dtype=torch.float16)
print(y.dtype)
y = torch.tensor([2.6, 4.7, 2.5], dtype=torch.float64)
print(y)
print(y.dtype)

torch.int64
tensor([1., 2., 3.])
torch.float32
torch.float16
tensor([2.6000, 4.7000, 2.5000], dtype=torch.float64)
torch.float64


## Moving to GPU
Why GPUs over CPUs for Machine Learning?

#### CPU (Central Processing Unit)
Designed for general-purpose computing\
Has few but very powerful cores\
Optimized for sequential processing (one task after another)\
Handles complex logic and branching well\
Good at low-latency tasks (fast single operations)


#### GPU (Graphics Processing Unit)
Designed for massively parallel processing\
Has thousands of smaller cores\
Excels at performing many identical operations simultaneously\
Best for mathematical and matrix-heavy computations\
Optimized for high-throughput tasks

In [22]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

t = torch.tensor([1., 2., 3.])
t_gpu = t.to(device)
print(t_gpu.device)

# move back to CPU (needed before NumPy conversion)
t_cpu = t_gpu.cpu()
print(t_cpu.numpy())

Using device: cpu
cpu
[1. 2. 3.]


### DISCUSSION

We explored the fundamental concepts of PyTorch tensors and their operations. In machine learning and deep learning, performance is highly dependent on hardware. CPUs are designed for sequential processing and general tasks, while GPUs are optimized for parallel computations, making them ideal for large-scale matrix and tensor operations.

We began by creating basic tensors and understanding their structure, including scalars, vectors, and higher-dimensional tensors. We then studied various tensor creation methods such as torch.rand(), torch.zeros(), torch.ones(), torch.eye(), torch.arange(), and torch.linspace().

Next, we explored tensor operations, including addition (+ vs torch.add()), element-wise multiplication (*), and matrix multiplication (@), along with their shape requirements and use cases.

We also examined reshaping techniques using view() and reshape(), where view() shares memory and requires contiguous tensors, while reshape() is more flexible and may create a copy if needed. In addition, we covered squeeze() and unsqueeze() for dimension manipulation and torch.stack() for combining tensors.

Further, we practiced indexing, aggregation functions (min, max, mean, sum), and datatype handling for efficient computation. Finally, we discussed GPU acceleration in PyTorch, where tensors can be moved between CPU and GPU using .to(device), enabling faster computation for large datasets.

### CONCLUSION

The objective of this lab was achieved. We gained a clear understanding of PyTorch fundamentals, including tensor operations, manipulation techniques, and GPU utilization for efficient deep learning computations.